name: Build and Deploy to Scaleway

on:
  push:
    branches:
      - main

env:
  APP_NAME: mtg-ai-agent

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t ${{ env.APP_NAME }}:${{ github.sha }} .

    - name: Save Docker image as tar file
      run: |
        docker save ${{ env.APP_NAME }}:${{ github.sha }} -o ${{ env.APP_NAME }}.tar

    - name: Upload artifact (Docker image)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-image
        path: ${{ env.APP_NAME }}.tar


      