services:
  app:
    image: "${APP_NAME:-app}:${APP_VERSION:-latest}"
    container_name: "${APP_NAME:-app}"
    restart: always
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      CHAINLIT_URL: "https://${APP_DOMAIN}"
      CHAINLIT_AUTH_SECRET: "${CHAINLIT_AUTH_SECRET}"
      OAUTH_GITHUB_CLIENT_ID: "${OAUTH_GITHUB_CLIENT_ID}"
      OAUTH_GITHUB_CLIENT_SECRET: "${OAUTH_GITHUB_CLIENT_SECRET}"
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME:-app}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME:-app}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME:-app}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${APP_NAME:-app}.loadbalancer.server.port=80"

  reverse-proxy:
    image: "traefik:v2.9"
    container_name: "traefik"
    restart: always
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik_net

networks:
  traefik_net:
    driver: bridge
