name: Build and Deploy to Scaleway

on:
  push:
    branches:
      - main

env:
  APP_NAME: mtg-ai-agent

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.APP_NAME }}:${{ github.sha }} .

      - name: Save Docker image as tar file
        run: docker save ${{ env.APP_NAME }}:${{ github.sha }} -o ${{ env.APP_NAME }}.tar

      - name: Upload artifact (Docker image)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-image
          path: ${{ env.APP_NAME }}.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-image

      - name: Use Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          save-config: true
          export-config: true
          version: v2.24.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}

      - name: Retrieve secrets from Scaleway
        uses: scaleway/action-scw-secret@v0
        with:
          secret-names: |
            openai-api-key
            chainlit-auth-secret
            email
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}

      - name: Transfer image and docker-compose to Scaleway instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SCW_SSH_HOST }}
          username: ${{ secrets.SCW_SSH_USER }}
          key: ${{ secrets.SCW_SSH_KEY }}
          source: "${{ env.APP_NAME }}.tar,docker-compose.yaml"
          target: "/home/${{ secrets.SCW_SSH_USER }}/"

      - name: Deploy on Scaleway instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SCW_SSH_HOST }}
          username: ${{ secrets.SCW_SSH_USER }}
          key: ${{ secrets.SCW_SSH_KEY }}
          envs: OPENAI_API_KEY,CHAINLIT_AUTH_SECRET,EMAIL,APP_NAME
          script: |
            cd /home/${{ secrets.SCW_SSH_USER }}
            docker image rm ${{ env.APP_NAME }}:${{ github.sha }} || true
            docker load -i ${{ env.APP_NAME }}.tar
            docker tag ${{ env.APP_NAME }}:${{ github.sha }} ${{ env.APP_NAME }}:latest
            docker compose down || true
            docker compose up -d
