name: Build and Deploy to Scaleway

on:
  push:
    branches:
      - main

env:
  APP_NAME: mtg-ai-agent
  APP_VERSION: ${{ github.sha }}
  APP_DOMAIN: chat.magicoracle.net

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.APP_NAME }}:${{ env.APP_VERSION }} .

      - name: Save Docker image as tar file
        run: docker save ${{ env.APP_NAME }}:${{ env.APP_VERSION }} -o ${{ env.APP_NAME }}.tar

      - name: Upload artifact (Docker image)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-image
          path: ${{ env.APP_NAME }}.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-image

      - name: Retrieve secrets from Scaleway
        uses: scaleway/action-scw-secret@v0
        with:
          secret-names: |
            email
            openai-api-key
            chainlit-auth-secret
            oauth-github-client-id
            oauth-github-client-secret
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}

      - name: Transfer image, docker-compose to Scaleway instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SCW_SSH_HOST }}
          username: ${{ secrets.SCW_SSH_USER }}
          key: ${{ secrets.SCW_SSH_KEY }}
          source: "${{ env.APP_NAME }}.tar,docker-compose.yaml"
          target: "/home/${{ secrets.SCW_SSH_USER }}/"

      - name: Deploy on Scaleway instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SCW_SSH_HOST }}
          username: ${{ secrets.SCW_SSH_USER }}
          key: ${{ secrets.SCW_SSH_KEY }}
          script_stop: true
          envs: >
            APP_NAME,
            APP_VERSION,
            APP_DOMAIN,
            EMAIL,
            OPENAI_API_KEY,
            CHAINLIT_URL,
            CHAINLIT_AUTH_SECRET,
            OAUTH_GITHUB_CLIENT_ID,
            OAUTH_GITHUB_CLIENT_SECRET
          script: |
            cd /home/${{ secrets.SCW_SSH_USER }}
            docker load -i ${{ env.APP_NAME }}.tar
            docker compose up -d --no-deps
            docker image prune -a -f
